id: user.user.compact
uuid: cf990905-0f4a-45bb-bd01-1ded661ddf02
targetEntityType: user
bundle: user
mode: compact
content:
  user_picture:
    label: hidden
    type: image
    settings:
      image_style: thumbnail
      image_link: content
    weight: 0
  member_for:
    visible: false
status: true
