id: user.user.default
uuid: d78a2fd6-4325-4f51-9d00-f2cd068f25ed
targetEntityType: user
bundle: user
mode: default
content:
  user_picture:
    label: hidden
    type: image
    settings:
      image_style: thumbnail
      image_link: content
    weight: 0
status: true
