id: authenticated
uuid: 515250c9-46bd-4611-ba06-6b8cfd63f1a7
label: 'Authenticated user'
weight: 1
permissions:
  - 'use text format plain_text'
  - 'use text format basic_html'
  - 'access content'
  - 'access comments'
  - 'post comments'
  - 'skip comment approval'
  - 'access site-wide contact form'
  - 'access user profiles'
  - 'restful get entity:activity'
  - 'restful post entity:activity'
  - 'restful delete entity:activity'
  - 'restful patch entity:activity'
  - 'restful get entity:adv'
  - 'restful post entity:adv'
  - 'restful delete entity:adv'
  - 'restful patch entity:adv'
  - 'restful get entity:adv_block_item'
  - 'restful post entity:adv_block_item'
  - 'restful delete entity:adv_block_item'
  - 'restful patch entity:adv_block_item'
  - 'restful get entity:adv_block'
  - 'restful post entity:adv_block'
  - 'restful delete entity:adv_block'
  - 'restful patch entity:adv_block'
  - 'restful get entity:store_catalog'
  - 'restful post entity:store_catalog'
  - 'restful delete entity:store_catalog'
  - 'restful patch entity:store_catalog'
  - 'restful get entity:city'
  - 'restful post entity:city'
  - 'restful delete entity:city'
  - 'restful patch entity:city'
  - 'restful get entity:district'
  - 'restful post entity:district'
  - 'restful delete entity:district'
  - 'restful patch entity:district'
  - 'restful get entity:coupon'
  - 'restful post entity:coupon'
  - 'restful delete entity:coupon'
  - 'restful patch entity:coupon'
  - 'restful get entity:node'
  - 'restful post entity:node'
  - 'restful delete entity:node'
  - 'restful patch entity:node'
  - 'restful get entity:share'
  - 'restful post entity:share'
  - 'restful delete entity:share'
  - 'restful patch entity:share'
  - 'restful get entity:share_catalog'
  - 'restful post entity:share_catalog'
  - 'restful delete entity:share_catalog'
  - 'restful patch entity:share_catalog'
  - 'restful get entity:share_comment'
  - 'restful post entity:share_comment'
  - 'restful delete entity:share_comment'
  - 'restful patch entity:share_comment'
  - 'restful get entity:store_comment'
  - 'restful post entity:store_comment'
  - 'restful delete entity:store_comment'
  - 'restful patch entity:store_comment'
  - 'restful get entity:store'
  - 'restful post entity:store'
  - 'restful delete entity:store'
  - 'restful patch entity:store'
  - 'restful get entity:user'
  - 'create share'
status: true
langcode: en
